import axios from "axios";
import Head from "next/head";
import { useEffect } from "react";
import Bg from "../components/Bg";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>GTCE : GitHub Twitter Card Embed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className="relative z-10">
        <NavBar />
      </div>
      <Bg />
    </>
  );
}
