import axios from "axios";
import Head from "next/head";
import { useEffect } from "react";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>GTCE : GitHub Twitter Card Embed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <body className="">
        <NavBar />
      </body>
    </>
  );
}
